[workspace]
members = [
    "programs/my_dex_project",
]

[profile.release]
overflow-checks = true
debug = true

[patch.crates-io]
spl-token-2022 = { git = "https://github.com/solana-labs/solana-program-library", branch = "master" }
